"""Single source of truth for the NEW RUN dial guidance.

Used BOTH by the studio's focus tooltips (studio.py: `from dials_help import DIALS as HELP`) AND by the
creative-director's system prompt (vlm_planner.py: `dial_guide()`), so the director understands the EXACT
same dials the user sees in the UI. Pure stdlib -> imports cleanly in either venv.
"""
import re

DIALS = {
    "mode": "[b]MODE[/b]\n[b]single[/b] — one clip from your PROMPT. If LENGTH needs more than one shot it\nauto-chains (same prompt, glued at the tails) — no LLM involved.\n[b]director[/b] — a vision model watches each shot's last frame and rewrites the\nprompt for the next shot, steering toward your DIRECTIVE. Pick it when the\nvideo should progress or tell a story.",
    "backend": "[b]BACKEND[/b]  (the video model)\n[b]LTX-2B[/b] — fast (~1s/step), lighter; best for quick drafts + iteration.\n[b]Wan-VACE-1.3B[/b] — slower (~7s/step + a slow decode) but clearly higher\nfidelity and better motion; renders at 480p / 16fps natively.\n[b]Wan turbo[/b] — CFG-distilled few-step Wan: much faster, near-Wan look; forces\nGUIDANCE to 1.0 and caps STEPS at 8 (~6 is the sweet spot).\nGUIDANCE auto-retunes when you switch (LTX 3.0 / Wan 5.0 / turbo 1.0).",
    "prompt": "[b]PROMPT[/b]  (the opening shot)\nBe concrete: subject + action + setting + style. Name the medium so it sticks\n('35mm film', 'oil painting', 'photoreal'). For an animal or person, keep the\nhead/face visible (profile or facing you) — turned-away or tiny faces blur.\nE.g. 'a red fox trotting through fresh snow at dawn, photoreal, side profile'.",
    "directive": "[b]DIRECTIVE[/b]  (director mode)\nThe destination the director steers toward, shot by shot — PROMPT is where the\nvideo starts, DIRECTIVE is where it ends up.\nRead by [b]Evolve[/b] ONLY: Hold and Balanced never show it to the director.\nE.g. PROMPT 'a calm sea at dawn' + DIRECTIVE 'a storm builds, then clears to a\nrainbow'. Blank = the run just holds the opening scene (behaves as Hold).",
    "anchors": "[b]ANCHORS[/b]  (the style leash)\nSubject + style tokens to keep in EVERY shot — the main defense against drift\nacross a long clip. Put the medium here so it persists.\nChained runs fold them into the prompt once, so every shot carries them.\nDirector mode: folded into shot 1 too, and every rewrite is checked — any\nanchor the rewrite dropped is re-appended automatically (enforced).\nE.g. 'brown horse, golden-hour, 35mm film' or 'watercolor, muted palette'.",
    "cond_strength": "[b]CONTINUITY[/b]  (0-1, chained runs)\nHow tightly each new shot holds the previous shot's last frames.\n[b]1.0[/b] — tightest; the scene/subject carries over (best for HOLD).\n[b]~0.6-0.8[/b] — looser; lets motion + scene evolve more between shots.\nRaise it if the subject drifts or morphs; lower it if a clip feels 'stuck'.",
    "steadiness": "[b]STEADINESS[/b]  (director mode)\nHow far the director may stray from the opening scene:\n[b]Hold[/b] — repair-only. Checks every 3rd seam and KEEPs the prompt unless the\nframe visibly drifted; static scenes skip the check entirely.\n[b]Balanced[/b] — every 3rd seam the director ALWAYS rewrites with gentle\nvariation (angle / light / pose) — no keep-gate.\n[b]Evolve[/b] — re-plans EVERY seam toward the DIRECTIVE. Requires a DIRECTIVE\nthat differs from the prompt; the form blocks queueing otherwise, because a\nblank directive would silently run as Hold.",
    "image": "[b]START IMAGE[/b]  (optional)\nA still to animate — shot 1 begins from this exact frame (image-to-video).\nPath relative to the studio, e.g. input/start.png. Must exist before you run;\nmatch it to your RESOLUTION's aspect ratio for best results.\nLeave blank to generate the opening from the PROMPT instead.",
    "res": "[b]RESOLUTION[/b]\nFrame size. 512 = fast drafts, 704 = balanced, 768 = sharpest.\nPeak VRAM is CAPPED: raising RES trades away max shot length (a fixed\npixel-frame budget per pass) instead of using more VRAM — so higher res means\nmore seams + render time, not OOM risk.\nWan renders ~480p natively and upscales lower settings automatically, so\n512-704 is plenty for it.",
    "seconds": "[b]LENGTH s[/b]  (total length)\nTotal video length. Length is nearly free — it just adds more chained shots\n(and render time). Exceed one shot's worth and it auto-chains.\nE.g. 12s at ~2.4s per shot is about 5-6 shots stitched together.",
    "seg": "[b]SEGMENT s[/b]  (shot length — director mode ONLY)\nSeconds requested for ONE model pass — the unit long videos are chained from.\nGrayed outside director mode because the engine ignores it there: single and\nauto-chain runs compute shot length from the VRAM budget (~20M pixel-frames\nper pass: frames ~= 20e6 / (W x H), snapped to the model's frame grid), so\nhigher RESOLUTION means shorter shots.\nDirector mode: your request is honored, still capped by that same budget.",
    "steps": "[b]STEPS[/b]  (quality vs time)\nDenoising iterations per shot. ~20 = fast draft, ~30 = good, ~40-50 = best\n(diminishing returns). Render time scales linearly with steps.\nWan looks good at ~20-30; LTX likes ~30-40.\nWan-turbo is a few-step distill: STEPS is capped at 8 (~6 is the sweet spot).",
    "cfg": "[b]GUIDANCE[/b]  (CFG — prompt adherence)\nHow hard the model steers toward your prompt. LTX ~3.0, Wan ~5.0 (auto-set\nwhen you switch BACKEND; override freely). Wan-turbo requires 1.0, enforced.\nToo high = fried / over-saturated; too low = loose, ignores the prompt.\nNudge down ~1 if colors cook — or keep it and add GUIDANCE RESCALE instead.",
    "seed": "[b]SEED[/b]\nThe random starting point. [b]Same seed + same settings = identical output.[/b]\nBlank = a fresh random seed every run; the drawn value is recorded with the\njob, so any keeper can be reproduced.\nFix it to change ONE thing at a time (tweak the prompt, keep the seed) and\ncompare fairly. 0 is just a fixed seed like any other.",
    "fps": "[b]FPS[/b]  (playback framerate)\n24 = cinematic, 30 = smoother. Drives the LTX backend.\nWan and Wan-turbo always render at their native 16fps (the right motion speed\nfor those models) regardless of this field.",
    "n_prompt": "[b]NEG[/b]  (negative prompt)\nWhat to steer AWAY from. The default is a tuned quality guard (blurry,\ndeformed, extra limbs, headless, etc.) — usually just leave it.\nAdd terms to fix a recurring problem, e.g. 'text, watermark, busy background'.",
    "name": "[b]NAME[/b]  (output file)\nSaves to outputs/NAME.mp4 (+ a frames folder). Spaces become dashes. Blank =\nauto 'job_HHMMSS'. If the name exists it auto-adds a suffix, so you never\noverwrite an earlier run.",
    "vram_reserve": "[b]RESERVE (GB)[/b]\nGB of the 8GB card held back for desktop responsiveness while a run is active.\nHigher = smoother UI; lower = more VRAM headroom for Wan. ~1.0 is the sweet\nspot. On an idle desktop you can safely drop it to 0.5 during heavy renders.",
    "sound_enabled": "[b]SOUND[/b]  (event alerts — master switch)\nGates ALL event sounds: run_done (a run lands in the ARCHIVE as done),\nrun_stall (the stall sentry fires), plus run_start and queue_empty.\nEach event plays its WAV from sfx/ (e.g. sfx/run_start.wav,\nsfx/queue_empty.wav) and stays silent if the file is absent. Pick the done\nand stall WAVs with the two dials below.\nA stalled run is AUTO-SUSPENDED even with sound off: graceful first, then a\ncheckpoint-preserving kill, with per-phase fuses so a slow decode is not\nmistaken for a stall. Resume from QUEUE/ARCHIVE.",
    "snd_done": "[b]DONE SOUND[/b]\nThe WAV that plays when a run lands in the ARCHIVE as done.\nThe list shows every .wav in sfx/ — drop your own files into that folder and\nthey appear here. Gated by the master SOUND switch.",
    "snd_stall": "[b]STALL SOUND[/b]\nThe WAV that plays when the stall sentry raises an alert.\nThe list shows every .wav in sfx/ — drop your own files into that folder and\nthey appear here. Gated by the master SOUND switch.",
    "cfg_rescale": "[b]GUIDANCE RESCALE[/b]  (advanced; opt-in, default off)\nFixes the fried / over-saturated / neon look of high GUIDANCE.\nAfter the CFG combine it renormalizes the noise prediction's standard\ndeviation back toward the conditional pass's (the classic guidance-rescale\ntrick) — taming the burn while costing less prompt adherence than simply\nlowering GUIDANCE would.\n[b]0.5[/b] = mild, [b]0.7[/b] = strong.\nLTX + Wan. No-op at GUIDANCE <= 1 and on Wan-turbo.",
    "cfg_interval": "[b]GUIDANCE SCHEDULE[/b]  (advanced; opt-in, default off)\nRuns the CFG uncond pass on only part of the denoise schedule. Each on-step\ncosts ~2x a no-CFG step, so trimming the schedule buys real speed at a slight\nfidelity cost.\n[b]0.0:0.3[/b] — front 30%; structure forms early, so this is the cheapest cut.\n[b]0.0:0.5[/b] — front half; the balanced default choice.\n[b]0.0:0.7[/b] — front 70%; the safest trim.\n[b]0.3:1.0[/b] — late 70%; guidance during detail refinement instead.\n[b]2[/b] / [b]3[/b] — every 2nd / 3rd step (a comb pattern).\n[b]WAN ONLY[/b] — LTX fuses cond+uncond into one batched forward, which is\nstructurally incompatible with per-step gating (it crashed real runs); the\nfield is grayed on other backends. No-op at GUIDANCE <= 1.",
    "wan_ref_anchor": "[b]IDENTITY ANCHOR[/b]  (advanced; opt-in, default off)\nPins every shot in a chain to shot 1's opening frame as a reference,\nstabilizing subject identity across a long video and fighting style/identity\ndrift. Wan / Wan-turbo only; chained (multi-shot) runs.",
    "blind_ab": "[b]⇄ BLIND A/B[/b]  (fair variable-isolation test)\nQueues TWO runs from the CURRENT form, identical except ONE variable you pick\n(A-value vs B-value), on ONE shared seed. Enqueue order + the A/B labels are\nrandomized, so the ARCHIVE hides which run is which (kind, variant, and the\nvaried value all read 'blind') until you press ↯ REVEAL. Rate them fairly with\n≷ RATE PAIR first, THEN reveal to see which setting won.",
}

_TAG = re.compile(r"\[/?[a-z][^\]]*\]")


def plain(text):
    """Strip Rich [tag] markup -> plain text (for feeding the language model)."""
    return _TAG.sub("", text or "")


def dial_guide():
    """Compact plain-text guide to every dial (markup stripped) for the director's system prompt. The key
    on the left is the EXACT config field name the director should emit."""
    lines = []
    for key, text in DIALS.items():
        g = re.sub(r"\s{2,}", " ", plain(text).replace("\n", " ")).strip()
        lines.append("- %s -> %s" % (key, g))
    return "\n".join(lines)
